import * as Raw from 'lucide-react';
const R = Raw as any;

// Safe re-exports with fallbacks to avoid TS/runtime mismatch
export const LogIn = R.LogIn || R.LogInIcon || R.default || ((p: any) => null);
export const LogOut = R.LogOut || ((p: any) => null);
export const Search = R.Search || ((p: any) => null);
export const Camera = R.Camera || ((p: any) => null);
export const User = R.User || ((p: any) => null);
export const Plus = R.Plus || ((p: any) => null);
export const ScanEye = R.ScanEye || ((p: any) => null);
export const Eye = R.Eye || ((p: any) => null);
export const EyeOff = R.EyeOff || ((p: any) => null);
export const Loader2 = R.Loader2 || ((p: any) => null);
export const AlertCircle = R.AlertCircle || ((p: any) => null);
export const CheckCircle = R.CheckCircle || ((p: any) => null);
export const XCircle = R.XCircle || ((p: any) => null);
export const Clock = R.Clock || ((p: any) => null);
export const AlertTriangle = R.AlertTriangle || ((p: any) => null);
export const ChevronDown = R.ChevronDown || ((p: any) => null);
export const ChevronUp = R.ChevronUp || ((p: any) => null);
export const ChevronRight = R.ChevronRight || ((p: any) => null);
export const ChevronLeft = R.ChevronLeft || ((p: any) => null);
export const Play = R.Play || ((p: any) => null);
export const Pause = R.Pause || ((p: any) => null);
export const RotateCcw = R.RotateCcw || ((p: any) => null);
export const FileText = R.FileText || ((p: any) => null);
export const Lock = R.Lock || ((p: any) => null);
export const Upload = R.Upload || ((p: any) => null);
export const ShieldCheck = R.ShieldCheck || ((p: any) => null);
export const ClipboardCheck = R.ClipboardCheck || ((p: any) => null);
export const Layers = R.Layers || ((p: any) => null);
export const Box = R.Box || ((p: any) => null);
export const Scissors = R.Scissors || ((p: any) => null);
export const Droplets = R.Droplets || ((p: any) => null);
export const Package = R.Package || ((p: any) => null);
export const LayoutDashboard = R.LayoutDashboard || ((p: any) => null);
export const Activity = R.Activity || ((p: any) => null);
export const TrendingUp = R.TrendingUp || ((p: any) => null);
export const TrendingDown = R.TrendingDown || ((p: any) => null);
export const Minus = R.Minus || ((p: any) => null);
export const Check = R.Check || ((p: any) => null);
export const ArrowRight = R.ArrowRight || ((p: any) => null);
export const X = R.X || ((p: any) => null);
export const Bell = R.Bell || ((p: any) => null);
export const Trash2 = R.Trash2 || ((p: any) => null);
export const Cpu = R.Cpu || ((p: any) => null);
export const Server = R.Server || ((p: any) => null);
export const Wifi = R.Wifi || ((p: any) => null);
export const HardDrive = R.HardDrive || ((p: any) => null);
export const Ticket = R.Ticket || ((p: any) => null);
export const ShieldAlert = R.ShieldAlert || ((p: any) => null);
export const Database = R.Database || ((p: any) => null);
export const Wrench = R.Wrench || ((p: any) => null);
export const Settings = R.Settings || ((p: any) => null);
export const RadioTower = R.RadioTower || ((p: any) => null);
export const Cable = R.Cable || ((p: any) => null);

export default R;
