import { db } from '../db';
import { controlCheckpoints, processSteps } from '../../shared/schema';
import { eq } from 'drizzle-orm';

/**
 * Seed Control Plan Checkpoints for Process 40.0 (Sparboom-SF)
 * Total: 57 checkpoints
 * QA-Validated: 24 checkpoints (22 "QA" + 2 "prod/QA")
 */

// Helper to compute requiresQaValidation
const requiresQaValidation = (verifiedBy: string) =>
    verifiedBy === "QA" || verifiedBy === "prod/QA";

async function seedProcess40Checkpoints() {
    console.log('🌱 Seeding Process 4 Control Plan Checkpoints...');

    // Find Process 4 (Spar Boom - SF) step IDs
    const process40Steps = await db
        .select()
        .from(processSteps)
        .where(eq(processSteps.processId, 4)); // Process 4 = Spar Boom - SF

    if (process40Steps.length === 0) {
        console.error('❌ Process 4 (Spar Boom - SF) not found. Please ensure the process exists before running this seed.');
        return;
    }

    // Map step numbers to step IDs
    const stepMap = new Map<string, number>();
    process40Steps.forEach(step => {
        stepMap.set(step.stepNumber, step.id);
    });

    const checkpoints = [
        // 40.01 Mould Preparation (4 checkpoints, 0 QA)
        {
            stepNumber: '40.01',
            processStep: '40.01',
            name: 'Cleaning of surface',
            characteristic: 'Cleaning of surface',
            specification: 'Free from dust, resin residuals, any Foreign objects',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Clean/Correct it before proceeding',
            sequence: 1,
        },
        {
            stepNumber: '40.01',
            processStep: '40.01',
            name: 'Check for damages',
            characteristic: 'Check for damages',
            specification: 'Free from damages',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Clean/Correct it before proceeding',
            sequence: 2,
        },
        {
            stepNumber: '40.01',
            processStep: '40.01',
            name: 'Release Agent(NC55) application',
            characteristic: 'Release Agent(NC55) application',
            specification: 'No runs, 100% coverage of product area',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 3,
        },
        {
            stepNumber: '40.01',
            processStep: '40.01',
            name: 'Release Agent(NC55) application timing',
            characteristic: 'Release Agent(NC55) application',
            specification: '20mins from application end',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Wait till achieved',
            sequence: 4,
        },

        // 40.02 Lower Process material placement (3 checkpoints, 0 QA)
        {
            stepNumber: '40.02',
            processStep: '40.02',
            name: 'Peel ply placement',
            characteristic: 'Peel ply placement',
            specification: 'R3500-R69000- all over width',
            tolerance: 'N/A',
            method: 'Visual & measure tape',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 1,
        },
        {
            stepNumber: '40.02',
            processStep: '40.02',
            name: 'CFM Placement in Leading edge side',
            characteristic: 'CFM Placement in Leading edge side',
            specification: 'R55000 to R64000 width=100 mm',
            tolerance: 'N/A',
            method: 'Visual & measure tape',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 2,
        },
        {
            stepNumber: '40.02',
            processStep: '40.02',
            name: 'Combi mesh',
            characteristic: 'Combi mesh',
            specification: '55000 mm to 68800 mm =width 700 mm',
            tolerance: 'N/A',
            method: 'Visual & measure tape',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 3,
        },

        // 40.03 Loading of Glass Rolls (5 checkpoints, 0 QA)
        {
            stepNumber: '40.03',
            processStep: '40.03',
            name: 'Material Description',
            characteristic: 'Material Description',
            specification: 'G1+G1,HMR-1/0-2340',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Ask to Store & QA',
            sequence: 1,
        },
        {
            stepNumber: '40.03',
            processStep: '40.03',
            name: 'Damages',
            characteristic: 'Damages',
            specification: 'Free from damages',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Hold the materials & Report to QA',
            sequence: 2,
        },
        {
            stepNumber: '40.03',
            processStep: '40.03',
            name: 'Contamination',
            characteristic: 'Contamination',
            specification: 'Free from contamination',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Hold the materials & Report to QA',
            sequence: 3,
        },
        {
            stepNumber: '40.03',
            processStep: '40.03',
            name: 'Batch No',
            characteristic: 'Batch No',
            specification: 'As per bagging',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Ask to Store & QA',
            sequence: 4,
        },
        {
            stepNumber: '40.03',
            processStep: '40.03',
            name: 'Material feeding from the rollers',
            characteristic: 'Material feeding from the rollers',
            specification: 'Manual feeding without damaging the layers',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 5,
        },

        // 40.04 Layup & Core material placement (20 checkpoints, 18 QA)
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Glass Layup Start',
            characteristic: 'Glass Layup Start',
            specification: 'R3500',
            tolerance: '±20mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 1,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Glass Layup End',
            characteristic: 'Glass Layup End',
            specification: 'R69000',
            tolerance: '±20mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 2,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Glass Layup-chordwise position tolerance',
            characteristic: 'Glass Layup-chordwise position tolerance',
            specification: 'Position tolerance',
            tolerance: '±5mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 3,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Glass overlap - in case of shortage',
            characteristic: 'Glass overlap - in case of shortage',
            specification: 'Overlap',
            tolerance: '200±20mm if once in 5layers',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 4,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Glass overlap restriction',
            characteristic: 'Glass overlap - in case of shortage',
            specification: 'Overlap restriction',
            tolerance: 'Not permitted in first/last layers & distance <2m between joints',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 5,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Lengthwise position tolerance',
            characteristic: 'Lengthwise position tolerance',
            specification: 'Position tolerance',
            tolerance: '±20mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 6,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Layup',
            characteristic: 'Layup',
            specification: 'Without wrinkle',
            tolerance: 'N/A',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 7,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Balsa batch No',
            characteristic: 'Balsa batch No',
            specification: 'Batch number',
            tolerance: 'As per bagging',
            method: 'Visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'As store or QA',
            sequence: 8,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Balsa 9.5mmStart',
            characteristic: 'Balsa 9.5mmStart',
            specification: 'R55170',
            tolerance: '±20mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 9,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Balsa 9.5mm End',
            characteristic: 'Balsa 9.5mm End',
            specification: 'R67500',
            tolerance: '±20mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 10,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Balsa 6.4mmStart',
            characteristic: 'Balsa 6.4mmStart',
            specification: 'R67628',
            tolerance: '±20mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 11,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Balsa 6.4mm End',
            characteristic: 'Balsa 6.4mm End',
            specification: 'R68592',
            tolerance: '±20mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 12,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Lengthwise position tolerance (Balsa)',
            characteristic: 'Lengthwise position tolerance (Balsa)',
            specification: 'Position tolerance',
            tolerance: '±20mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 13,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'chordwise position tolerance',
            characteristic: 'chordwise position tolerance',
            specification: 'Position tolerance',
            tolerance: '±5mm',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 14,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Balsa chamfer in lengthwise @R67500',
            characteristic: 'Balsa chamfer in lengthwise @R67500',
            specification: 'Chamfer ratio',
            tolerance: '1:20',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 15,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Core material placement step allowed',
            characteristic: 'Core material placement step allowed',
            specification: 'Step tolerance',
            tolerance: '±0.5mm',
            method: 'Visual',
            verifiedBy: 'prod/QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 16,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Moisture at Balsa',
            characteristic: 'Moisture at Balsa',
            specification: 'Moisture content',
            tolerance: '5 to 14%',
            method: 'Moisture meter',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 17,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Balsa chamfer in lengthwise at Start & end',
            characteristic: 'Balsa chamfer in lengthwise at Start & end',
            specification: 'Chamfer ratio',
            tolerance: '1:20',
            method: 'Mould marking/measure tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 18,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Glass cut at TIP',
            characteristic: 'Glass cut at TIP',
            specification: 'Cut profile',
            tolerance: 'As per mold profile',
            method: 'Visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 19,
        },
        {
            stepNumber: '40.04',
            processStep: '40.04',
            name: 'Part Identification paper Placement',
            characteristic: 'Part Identification paper Placement',
            specification: 'Placement position',
            tolerance: 'At R68000mm & R3800mm placed in centre',
            method: 'Visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 20,
        },

        // 40.05 Upper Process materials placement (5 checkpoints, 1 prod/QA)
        {
            stepNumber: '40.05',
            processStep: '40.05',
            name: 'Before placing upper process materials layup should be',
            characteristic: 'Before placing upper process materials layup should be',
            specification: 'Cleanliness',
            tolerance: 'Free from inclusions, Foreign materials',
            method: 'Visual',
            verifiedBy: 'prod/QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 1,
        },
        {
            stepNumber: '40.05',
            processStep: '40.05',
            name: 'Peel ply placement',
            characteristic: 'Peel ply placement',
            specification: 'R3500mm-R69000mm all over width',
            tolerance: 'N/A',
            method: 'measure tape',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 2,
        },
        {
            stepNumber: '40.05',
            processStep: '40.05',
            name: 'Mesh offset',
            characteristic: 'Mesh offset',
            specification: 'Root to 54;100mm, 54 to 68.8;120mm vacuum side',
            tolerance: 'N/A',
            method: 'measure tape',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 3,
        },
        {
            stepNumber: '40.05',
            processStep: '40.05',
            name: 'Mesh overlap',
            characteristic: 'Mesh overlap',
            specification: 'Overlap',
            tolerance: '±10mm',
            method: 'measure tape',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 4,
        },
        {
            stepNumber: '40.05',
            processStep: '40.05',
            name: 'Release film overlap',
            characteristic: 'Release film overlap',
            specification: 'Overlap',
            tolerance: '10-20mm',
            method: 'measure tape',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 5,
        },

        // 40.06 Vacuum & Test (2 checkpoints, 2 QA)
        {
            stepNumber: '40.06',
            processStep: '40.06',
            name: 'Vacuum drops',
            characteristic: 'Vacuum drops',
            specification: 'Vacuum leakage',
            tolerance: '20mbar in 10mins',
            method: 'Vacuum gauge, stop watch',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 1,
        },
        {
            stepNumber: '40.06',
            processStep: '40.06',
            name: 'Pre-heat of Mould',
            characteristic: 'Pre-heat of Mould',
            specification: 'Temperature',
            tolerance: '40°C',
            method: 'IR Gun',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Wait till achieved',
            sequence: 2,
        },

        // 40.07 Infusion (4 checkpoints, 4 QA)
        {
            stepNumber: '40.07',
            processStep: '40.07',
            name: 'Resin:Hardener Grade',
            characteristic: 'Resin:Hardener Grade',
            specification: 'Material grade',
            tolerance: 'Leuna; Infu 1a/Hard 175 or ABC; YD 585 / TH 7255E, TH 7257E',
            method: 'Label visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 1,
        },
        {
            stepNumber: '40.07',
            processStep: '40.07',
            name: 'Batch No',
            characteristic: 'Batch No',
            specification: 'Batch number',
            tolerance: 'As per package',
            method: 'Visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Hold the materials & Inform to Stores',
            sequence: 2,
        },
        {
            stepNumber: '40.07',
            processStep: '40.07',
            name: 'Mix ratio of R:H',
            characteristic: 'Mix ratio of R:H',
            specification: 'Mix ratio',
            tolerance: '100:32±1.5',
            method: 'Weighing balance',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Inform to Maintenance',
            sequence: 3,
        },
        {
            stepNumber: '40.07',
            processStep: '40.07',
            name: 'Infusion Resin temperature',
            characteristic: 'Infusion Resin temperature',
            specification: 'Temperature',
            tolerance: '<40°C',
            method: 'IR Gun',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Inform to Maintenance',
            sequence: 4,
        },

        // 40.08 Curing (2 checkpoints, 0 QA)
        {
            stepNumber: '40.08',
            processStep: '40.08',
            name: 'Curing cycle',
            characteristic: 'Curing cycle',
            specification: 'Duration & temperature',
            tolerance: '5hrs 30min @ 85°C',
            method: 'timer',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 1,
        },
        {
            stepNumber: '40.08',
            processStep: '40.08',
            name: 'Blanket coverage',
            characteristic: 'Blanket coverage',
            specification: 'Coverage timing',
            tolerance: 'After 4hrs of curing cycle start',
            method: 'System',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Inform to Maintenance',
            sequence: 2,
        },

        // 40.09 Debagging & Demould (4 checkpoints, 0 QA)
        {
            stepNumber: '40.09',
            processStep: '40.09',
            name: 'Debagging Temperature',
            characteristic: 'Debagging Temperature',
            specification: 'Temperature',
            tolerance: '≤65°C',
            method: 'IR Gun',
            verifiedBy: 'Prod',
            sampleSize: '1 (once in 10 parts)',
            reactionPlan: 'Wait till achieved',
            sequence: 1,
        },
        {
            stepNumber: '40.09',
            processStep: '40.09',
            name: 'Debagging',
            characteristic: 'Debagging',
            specification: 'Cleanliness',
            tolerance: 'Free from process materials',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 2,
        },
        {
            stepNumber: '40.09',
            processStep: '40.09',
            name: 'Radius marking on part each meter',
            characteristic: 'Radius marking on part each meter',
            specification: 'Marking requirement',
            tolerance: 'with mould marking From R3500 to 69000',
            method: 'Visual',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Correct it before proceeding',
            sequence: 3,
        },
        {
            stepNumber: '40.09',
            processStep: '40.09',
            name: 'Demoulding Temperature',
            characteristic: 'Demoulding Temperature',
            specification: 'Temperature',
            tolerance: '≤60°C',
            method: 'IR Gun',
            verifiedBy: 'Prod',
            sampleSize: '1',
            reactionPlan: 'Wait till achieved',
            sequence: 4,
        },

        // 40.10 Trimming (2 checkpoints, 2 QA)
        {
            stepNumber: '40.10',
            processStep: '40.10',
            name: 'Width',
            characteristic: 'Width',
            specification: 'Maximum width',
            tolerance: 'max Width of spar boom 810mm from R59M, width 300mm from 69M',
            method: 'Visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'NCR & Repair',
            sequence: 1,
        },
        {
            stepNumber: '40.10',
            processStep: '40.10',
            name: 'Trimming',
            characteristic: 'Trimming',
            specification: 'Quality',
            tolerance: 'Free from damage',
            method: 'Visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'NCR & Repair',
            sequence: 2,
        },

        // 40.11 Inspection (5 checkpoints, 5 QA)
        {
            stepNumber: '40.11',
            processStep: '40.11',
            name: 'Light Inspection',
            characteristic: 'Light Inspection',
            specification: 'Surface quality',
            tolerance: 'Free from dry layer, air in laminate, layer fold, wrinkles, Dull area',
            method: 'Visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'Repair to meet requirement',
            sequence: 1,
        },
        {
            stepNumber: '40.11',
            processStep: '40.11',
            name: 'Tg',
            characteristic: 'Tg',
            specification: 'Glass transition temperature',
            tolerance: '≥50°C',
            method: 'DSC',
            verifiedBy: 'QA',
            sampleSize: '15±3 grams',
            reactionPlan: 'Repair to meet requirement',
            sequence: 2,
        },
        {
            stepNumber: '40.11',
            processStep: '40.11',
            name: 'FWF',
            characteristic: 'FWF',
            specification: 'Fiber weight fraction',
            tolerance: '73±2%',
            method: 'muffle furnace',
            verifiedBy: 'QA',
            sampleSize: '20 to 100 grms',
            reactionPlan: 'Repair to meet requirement',
            sequence: 3,
        },
        {
            stepNumber: '40.11',
            processStep: '40.11',
            name: 'Width',
            characteristic: 'Width',
            specification: 'Maximum width',
            tolerance: 'max Width of spar boom 810mm from R59M, width 300mm from 69M',
            method: 'Measuring tape',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'NCR & Repair',
            sequence: 4,
        },
        {
            stepNumber: '40.11',
            processStep: '40.11',
            name: 'Part is ok as per the requirements',
            characteristic: 'Part is ok as per the requirements',
            specification: 'Final acceptance',
            tolerance: 'Put Green sticker',
            method: 'Visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'NCR & Repair',
            sequence: 5,
        },

        // 40.12 Storage (1 checkpoint, 1 QA)
        {
            stepNumber: '40.12',
            processStep: '40.12',
            name: 'Store in racks',
            characteristic: 'Store in racks',
            specification: 'Storage condition',
            tolerance: 'Without damages',
            method: 'Visual',
            verifiedBy: 'QA',
            sampleSize: '1',
            reactionPlan: 'NCR & Repair',
            sequence: 1,
        },
    ];

    // Insert checkpoints
    let insertedCount = 0;
    let qaCount = 0;

    for (const checkpoint of checkpoints) {
        const stepId = stepMap.get(checkpoint.stepNumber);
        if (!stepId) {
            console.warn(`⚠️  Step ${checkpoint.stepNumber} not found, skipping checkpoint: ${checkpoint.name}`);
            continue;
        }

        await db.insert(controlCheckpoints).values({
            stepId,
            processStep: checkpoint.processStep,
            name: checkpoint.name,
            characteristic: checkpoint.characteristic,
            specification: checkpoint.specification,
            tolerance: checkpoint.tolerance,
            method: checkpoint.method,
            verifiedBy: checkpoint.verifiedBy,
            requiresQaValidation: requiresQaValidation(checkpoint.verifiedBy),
            sampleSize: checkpoint.sampleSize,
            reactionPlan: checkpoint.reactionPlan,
            sequence: checkpoint.sequence,
            isGating: true,
        });

        insertedCount++;
        if (requiresQaValidation(checkpoint.verifiedBy)) {
            qaCount++;
        }
    }

    console.log(`✅ Inserted ${insertedCount} checkpoints for Process 40.0`);
    console.log(`   - QA-validated checkpoints: ${qaCount}`);
    console.log(`   - Prod-only checkpoints: ${insertedCount - qaCount}`);
}

// Run the seed
seedProcess40Checkpoints()
    .then(() => {
        console.log('✅ Seed completed successfully');
        process.exit(0);
    })
    .catch((error) => {
        console.error('❌ Seed failed:', error);
        process.exit(1);
    });
